name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: build plugin
        run: |
          zip wweir-tools.bobplugin LICENSE info.json icon.png *.js

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.bobplugin"
          token: ${{ secrets.GITHUB_TOKEN }}
